apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${BL_service}
  namespace: ${namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: business-layer
  template:
    metadata:
      name: business-layer
      labels:
        name: business-layer
        app: business-layer
    spec:
      serviceAccountName: api-service-account
      containers:
      - name: business-layer
        image: ${BL_image}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8088
